development:
  adapter: postgresql
  database: sample_app_devel
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sample_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sample_app_production
  pool: 5
  timeout: 5000
